Controllers/GoodsController.cs
using OnlineShoppingMall.Models.Cart;
using OnlineShoppingMall.Models.Good;
using OnlineShoppingMall.Models.UserInformation;
using OnlineShoppingMall.Services;
using System;
using System.Web.Mvc;

namespace OnlineShoppingMall.Controllers
{
    public class GoodsController : Controller
    {

        private GoodsService goodsService;
        private GoodsService Service { get { if (goodsService == null) { goodsService = new GoodsService(); } return goodsService; } }
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult InsertGoodsData(FormCollection form)
        {
            /*Goods goods = new Goods();

            string name = form["userId"];
            string explanation = form["password"];
            string price = form["password"];
            string stock = form["password"];
            string categoryId = form["password"];
            string stardDate = form["password"];
            string endDate = form["password"];

            goods.Name = name;
            goods.Explanation = explanation;
            goods.Price = int.Parse(price);
            goods.Stock = int.Parse(stock);
            goods.CategoryId = int.Parse(categoryId);
            goods.StardDate = DateTime.Parse(stardDate);
            goods.EndDate = DateTime.Parse(endDate);

            var data = Service.InsertGoodsData(goods);
*/
            return View();
        }
    }
}

Controllers/LoginController.cs
using OnlineShoppingMall.Models.User;
using OnlineShoppingMall.Models.UserInformation;
using OnlineShoppingMall.Services;
using System;
using System.Web.Mvc;
using System.Web.Services.Description;


namespace OnlineShoppingMall.Controllers
{
    public class LoginController : Controller
    {
        private LoginService loginService;
        private LoginService Service { get { if (loginService == null) { loginService = new LoginService(); } return loginService; } }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UserAccount(FormCollection form)
        {
            UserAccount userAccount = new UserAccount();

            string userId = form["userId"];
            string password = form["password"];

            userAccount.UserId = userId;
            userAccount.Password = password;

            Service.AddUserAccount(userAccount);

            return View("Index");
        }

        [HttpPost]
        public ActionResult UserAccountInfo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddUserAccountInfo(UserInfo userInfo)
        {
            var result = Service.AddUserAccountInfo(userInfo);

            return View("UserAccount");
        }

        
        public ActionResult FindId()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FindedId(FormCollection form)
        {
            UserInfo userInfo = new UserInfo();

            var name = form["name"];
            var birth = DateTime.Parse(form["birth"]);

            userInfo.Name = name;
            userInfo.Birth = birth;

            var message = Service.FindID(userInfo);

            ViewBag.Message = message;

            return View();
        }

        public ActionResult FindPassword()
        {
            return View();
        }


        public ActionResult FindedPassword(FormCollection form)
        {
            var id = form["userId"];

            var message = Service.FindPassword(id);

            ViewBag.Message = message;

            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Tawooly's Online Shopping Mall</title>
    <link rel="stylesheet" href="~/Content/CSS/Layout.css">

    <script src="~/Content/JavaScript/LayoutScript.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>
<body>
    <div class="title_bar">
        <div>
            <label class="home_font">
                @Html.ActionLink("Tawooly's Online Shopping Mall", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </label>
        </div>
        <div>
            <ul class="layout_ul">
                <li class="layout_li">@Html.ActionLink("ログイン", "Index", "Login")</li>
                <li class="layout_li">@Html.ActionLink("納品", "Index", "Goods")</li>
                <li class="cart_font">@Html.ActionLink("🛒", "Cart", "Home")</li>
            </ul>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer>
            <hr />
            <p>&copy; @DateTime.Now.Year - Tawooly's Online Shopping Mall</p>
            <h3>@Session["Message"]</h3>
            <hr />
        </footer>
    </div>
</body>
</html>